### ISSUE TITLE
WorldlyTooltips for fluid tanks need to show all the fluid inventory amounts

### ISSUE THREAD

**Issue by Josharias** [Terasology/Machines#20]
- There are definitely some shenanigans involved with getting first fluids.  Maybe this feature will help eliminate needing the first fluid slot.

**Comment by jdrueckert** [comment]
I believe that "fluid inventory amount" refers to what's by now part of the WorldyTooltip at the top of below screenshot, so I'll close this as done.
![image](https://user-images.githubusercontent.com/29981695/166120517-b4e1685c-e046-4d1b-b23b-b40f86c56178.png)
