### ISSUE TITLE
Restrict Fluid Pipes from transferring more than one liquid at once

### ISSUE THREAD

**Issue by Josharias** [Terasology/Machines#5]
I want fluid pipes to only allow one type of liquid to be transferred at one time so that real world is more simulated in that when you put two liquids in the same pipe they mix together,  we dont have liquid mixing,  so it should be avoided.
- possibly a 1 second delay between fluid types over the same pipe?  This would allow continuous pumping of particular liquids without getting overridden by a different connection.
- For bonus points, add some sort of visual indicator of what fluid is currently being transported.

**Comment by skaldarnar** [comment]
Do fluids currently have a base color, or is there some other way for simply representing each fluid by a color?

**Comment by Josharias** [comment]
Fluids that are a substance from SubstanceMatters will have a base color.  One might also be able to use the FluidRenderer.getTexture() to provide a visual.

**Comment by 4Denthusiast** [comment]
The way to access a fluid's texture has been changed to fluidRegistry.getFluidTexture to get it as an image or FluidContainerAssetResolver.getFluidBaseUri to get it as a Texture via the asset manager.

**Comment by jdrueckert** [comment]
To be honest, I'm not sure if we even have any pipe sinks that accept different types of fluids at once.
I think I'll close this for now and we can reopen and revisit it, if this comes up as an actual usability issue again.
